FROM php:7.3-cli
ENV http_proxy 172.19.1.179:3128
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
FROM php:7.3-fpm
RUN apt-get update -y \
  && apt-get install -y \
     libxml2-dev \
  && apt-get clean -y \
  && docker-php-ext-install soap
CMD [ "php", "soap_client.php"]